/* ============================================================
   WaniPharm curriculum data
   Source: ./database/  (KKU Pharmacology lecture notes,
   fact-checked vs Katzung Basic & Clinical Pharmacology)

   Each item:
     id       unique key
     type     'stem' | 'class' | 'drug'
     level    1..13
     char     text shown on the card
     meaning  accepted answers for the PRIMARY question
              (stem = meaning, class = mechanism/effect, drug = class)
     reading  OPTIONAL accepted answers for a 2nd "Key fact" question
     mnemonic memory hook (mainly for stems/affixes)
     info     one-line detail shown in the item sheet / on a miss
     requires ids that must reach Guru before this unlocks
   ============================================================ */
window.WANIPHARM_DATA = [

/* ==================================================================
   LEVEL 1 — Cholinergic receptors & transmission
   ================================================================== */
{id:'ach', type:'stem', level:1, char:'Acetylcholine', meaning:['cholinergic neurotransmitter','cholinergic','parasympathetic neurotransmitter'],
 mnemonic:'ACh is the "ah-choo" of rest-and-digest — it fires every preganglionic nerve, all parasympathetic targets, the NMJ, and sweat glands.',
 info:'Neurotransmitter at ALL preganglionic fibres, parasympathetic postganglionic, somatic NMJ, and sympathetic sweat glands.', requires:[]},
{id:'m2', type:'stem', level:1, char:'M₂ receptor', meaning:['slows the heart','decreases heart rate','heart muscarinic receptor'],
 mnemonic:'TWO hearts beat slower together — M2 sits on the heart (Gi) and drops the rate.',
 info:'Muscarinic M2: heart (SA/AV node), Gi → ↓cAMP & ↑K⁺ → ↓HR, ↓conduction. M1/M3/M5 = Gq (excitatory); M2/M4 = Gi (inhibitory).', requires:[]},
{id:'m3', type:'stem', level:1, char:'M₃ receptor', meaning:['smooth muscle contraction','gland secretion','smooth muscle and glands'],
 mnemonic:'M-THREE = Tears, Tinkle, Tummy — M3 squeezes smooth muscle and opens glands.',
 info:'Muscarinic M3 (Gq): smooth muscle contraction, gland secretion, miosis, bladder detrusor, NO-mediated vasodilation.', requires:[]},
{id:'nicotinic', type:'stem', level:1, char:'Nicotinic receptor', meaning:['ligand-gated ion channel','nicotinic'],
 mnemonic:'Nicotine flips a fast switch — nicotinic receptors are ligand-gated Na⁺/K⁺ channels.',
 info:'Nicotinic = ligand-gated ion channel. NN at autonomic ganglia & adrenal medulla; NM at the neuromuscular junction.', requires:[]},
{id:'ache', type:'stem', level:1, char:'Acetylcholinesterase', meaning:['breaks down acetylcholine','degrades acetylcholine','terminates ach'],
 mnemonic:'AChE is the clean-up crew (~600,000 ACh/min) — block it and ACh piles up.',
 info:'Enzyme that hydrolyses ACh → choline + acetate, terminating cholinergic signalling.', requires:[]},

{id:'musc_agonist', type:'class', level:1, char:'Muscarinic agonists', meaning:['activate muscarinic receptors','mimic acetylcholine','cholinomimetic'],
 reading:['sludge','salivation lacrimation urination diarrhea'],
 info:'Direct cholinomimetics. Toxidrome = SLUDGE/BBB (salivation, lacrimation, urination, diarrhoea, GI, emesis, bronchospasm, bradycardia). Antidote: atropine.', requires:['m3']},
{id:'ache_inh', type:'class', level:1, char:'AChE inhibitors', meaning:['block acetylcholinesterase','increase acetylcholine','indirect cholinomimetic'],
 info:'Indirect cholinomimetics — raise synaptic ACh. Used in myasthenia gravis, NMB reversal, Alzheimer’s, glaucoma; toxicity = cholinergic crisis.', requires:['ache']},
{id:'musc_antag', type:'class', level:1, char:'Muscarinic antagonists', meaning:['block muscarinic receptors','anticholinergic','antimuscarinic'],
 reading:['hot dry blind mad','anticholinergic toxidrome'],
 info:'Anticholinergics. Block effects: mydriasis, tachycardia, bronchodilation, ↓secretions, urinary retention. Toxidrome: hot, dry, blind, mad.', requires:['m3']},

{id:'bethanechol', type:'drug', level:1, char:'Bethanechol', meaning:['muscarinic agonist'],
 reading:['urinary retention','postoperative ileus'],
 info:'Muscarinic-selective agonist, AChE-resistant. Use: post-op/neurogenic urinary retention and ileus. No nicotinic effect.', requires:['musc_agonist']},
{id:'pilocarpine', type:'drug', level:1, char:'Pilocarpine', meaning:['muscarinic agonist'],
 reading:['glaucoma','xerostomia'],
 info:'Tertiary-amine alkaloid (crosses BBB). Use: glaucoma (topical) and xerostomia in Sjögren’s.', requires:['musc_agonist']},
{id:'neostigmine', type:'drug', level:1, char:'Neostigmine', meaning:['ache inhibitor','acetylcholinesterase inhibitor'],
 reading:['myasthenia gravis','reverses neuromuscular blockade'],
 info:'Quaternary carbamate (no BBB). Use: myasthenia gravis, reversal of non-depolarising NMB, post-op ileus/retention.', requires:['ache_inh']},
{id:'atropine', type:'drug', level:1, char:'Atropine', meaning:['muscarinic antagonist','anticholinergic'],
 reading:['bradycardia','organophosphate antidote'],
 info:'Prototype antimuscarinic (crosses BBB). Use: symptomatic bradycardia/AV block, organophosphate poisoning (+2-PAM), pre-anaesthetic.', requires:['musc_antag']},

/* ==================================================================
   LEVEL 2 — Cholinergic toxicology & neuromuscular
   ================================================================== */
{id:'organophosphate', type:'stem', level:2, char:'Organophosphates', meaning:['irreversible ache inhibitor','irreversible acetylcholinesterase inhibitor'],
 mnemonic:'Organophosphates "age" like a covalent marriage — once aged, the AChE bond is permanent.',
 info:'Irreversible AChE inhibitors (insecticides: malathion, parathion; nerve agents: sarin). "Aging" makes the bond permanent.', requires:['ache']},
{id:'nmj_blocker', type:'class', level:2, char:'Neuromuscular blockers', meaning:['paralyze skeletal muscle','block nm receptor','muscle relaxants'],
 info:'Act at the NM (nicotinic) receptor of the NMJ for surgical paralysis. Depolarising (succinylcholine) vs non-depolarising (-curium/-curonium).', requires:['nicotinic']},
{id:'physostigmine', type:'drug', level:2, char:'Physostigmine', meaning:['ache inhibitor','acetylcholinesterase inhibitor'],
 reading:['anticholinergic toxicity antidote','crosses bbb'],
 info:'Tertiary amine — crosses BBB. Antidote for anticholinergic (e.g. atropine) toxicity.', requires:['ache_inh']},
{id:'pralidoxime', type:'drug', level:2, char:'Pralidoxime (2-PAM)', meaning:['acetylcholinesterase reactivator','reactivates ache'],
 reading:['give before aging','organophosphate poisoning'],
 info:'Regenerates AChE in organophosphate poisoning — must be given BEFORE aging. Useless in carbamate toxicity. Pair with atropine.', requires:['organophosphate']},
{id:'donepezil', type:'drug', level:2, char:'Donepezil', meaning:['ache inhibitor','acetylcholinesterase inhibitor'],
 reading:['alzheimer disease'],
 info:'Central AChE inhibitor, long t½ (~70h). Use: mild–moderate Alzheimer’s disease.', requires:['ache_inh']},
{id:'ipratropium', type:'drug', level:2, char:'Ipratropium', meaning:['muscarinic antagonist','anticholinergic'],
 reading:['copd','short acting'],
 info:'Inhaled short-acting antimuscarinic (SAMA). Use: COPD, acute asthma.', requires:['musc_antag']},
{id:'tiotropium', type:'drug', level:2, char:'Tiotropium', meaning:['muscarinic antagonist','anticholinergic'],
 reading:['copd maintenance','long acting'],
 info:'Inhaled long-acting antimuscarinic (LAMA). Use: maintenance COPD.', requires:['musc_antag']},
{id:'succinylcholine', type:'drug', level:2, char:'Succinylcholine', meaning:['depolarizing neuromuscular blocker','depolarizing nmb'],
 reading:['rapid intubation','hydrolyzed by bche'],
 info:'Depolarising NM agonist → phase I block. Use: rapid-sequence intubation. Hydrolysed by plasma BChE.', requires:['nmj_blocker']},
{id:'rocuronium', type:'drug', level:2, char:'Rocuronium', meaning:['nondepolarizing neuromuscular blocker','nondepolarizing nmb'],
 reading:['surgical relaxant','reversed by neostigmine'],
 info:'Non-depolarising NM antagonist. Surgical muscle relaxant; reversed by neostigmine (+atropine).', requires:['nmj_blocker']},

/* ==================================================================
   LEVEL 3 — Adrenergic receptors & transmission
   ================================================================== */
{id:'ne', type:'stem', level:3, char:'Norepinephrine', meaning:['adrenergic neurotransmitter','adrenergic','sympathetic neurotransmitter'],
 mnemonic:'NE is the sympathetic messenger — made Tyrosine→DOPA→Dopamine→NE (tyrosine hydroxylase = rate-limiting).',
 info:'Main sympathetic postganglionic transmitter. Terminated by reuptake (NET); metabolised by MAO/COMT → VMA.', requires:[]},
{id:'a1', type:'stem', level:3, char:'α₁ receptor', meaning:['vasoconstriction','raises blood pressure'],
 mnemonic:'α-ONE = squeeze: one tight fist around blood vessels → vasoconstriction & mydriasis.',
 info:'α₁ (Gq → ↑IP₃/Ca²⁺): vasoconstriction, mydriasis, bladder/prostate sphincter contraction, ↑BP.', requires:[]},
{id:'a2', type:'stem', level:3, char:'α₂ receptor', meaning:['decreases ne release','autoreceptor','reduces sympathetic outflow'],
 mnemonic:'α-TWO says "you’ve had enough, NE" — presynaptic autoreceptor that shuts off NE release.',
 info:'α₂ (Gi → ↓cAMP): presynaptic autoinhibition of NE release; ↓aqueous humour; ↓insulin.', requires:[]},
{id:'b1', type:'stem', level:3, char:'β₁ receptor', meaning:['increases heart rate','stimulates the heart'],
 mnemonic:'You have ONE heart — β1 speeds it up and ↑renin.',
 info:'β₁ (Gs → ↑cAMP): ↑HR, ↑contractility, ↑conduction; ↑renin from JG cells.', requires:[]},
{id:'b2', type:'stem', level:3, char:'β₂ receptor', meaning:['bronchodilation','smooth muscle relaxation'],
 mnemonic:'You have TWO lungs — β2 opens the airways and relaxes smooth muscle.',
 info:'β₂ (Gs): bronchodilation, vasodilation, uterine relaxation, ↑glycogenolysis, K⁺ uptake/tremor.', requires:[]},

{id:'a1_agonist', type:'class', level:3, char:'α₁ agonists', meaning:['vasoconstrictors','raise blood pressure'],
 info:'Selective α₁ agonists → vasoconstriction. Uses: nasal decongestant, hypotension, mydriasis; reflex bradycardia.', requires:['a1']},
{id:'b2_agonist', type:'class', level:3, char:'β₂ agonists', meaning:['bronchodilators','relax bronchial smooth muscle'],
 info:'Selective β₂ agonists → bronchodilation (asthma/COPD) and tocolysis. SABA vs LABA.', requires:['b2']},
{id:'catecholamine', type:'class', level:3, char:'Catecholamines', meaning:['direct adrenergic agonists','direct sympathomimetics'],
 reading:['not oral','brief duration'],
 info:'NE, Epi, isoproterenol, dopamine, dobutamine. Rapid onset, brief, not oral (MAO/COMT), poor CNS entry.', requires:['b1']},

{id:'phenylephrine', type:'drug', level:3, char:'Phenylephrine', meaning:['α₁ agonist','alpha 1 agonist'],
 reading:['nasal decongestant','mydriatic'],
 info:'Selective α₁ agonist. Use: decongestant, raise BP, mydriasis (without cycloplegia).', requires:['a1_agonist']},
{id:'salbutamol', type:'drug', level:3, char:'Salbutamol (Albuterol)', meaning:['β₂ agonist','beta 2 agonist'],
 reading:['saba','acute asthma'],
 info:'Short-acting β₂ agonist (SABA). Use: acute asthma/bronchospasm, premature labour.', requires:['b2_agonist']},
{id:'salmeterol', type:'drug', level:3, char:'Salmeterol', meaning:['β₂ agonist','beta 2 agonist'],
 reading:['laba','asthma maintenance'],
 info:'Long-acting β₂ agonist (LABA). Use: maintenance asthma/COPD (with an inhaled steroid).', requires:['b2_agonist']},
{id:'epinephrine', type:'drug', level:3, char:'Epinephrine', meaning:['nonselective adrenergic agonist','alpha and beta agonist'],
 reading:['anaphylaxis','cardiac arrest'],
 info:'α & β agonist. Drug of choice for anaphylaxis (IM); also cardiac arrest, with local anaesthetics. Low dose β2 → ↓TPR; high dose α1 → ↑TPR.', requires:['catecholamine']},
{id:'ne_drug', type:'drug', level:3, char:'Norepinephrine (drug)', meaning:['alpha and beta1 agonist','vasopressor'],
 reading:['septic shock'],
 info:'α₁/α₂/β₁ agonist (little β₂). ↑systolic+diastolic BP → reflex bradycardia. First-line vasopressor in septic shock.', requires:['catecholamine']},
{id:'dopamine', type:'drug', level:3, char:'Dopamine', meaning:['dose-dependent adrenergic agonist'],
 reading:['cardiogenic shock'],
 info:'Dose-dependent: low → D₁ (renal vasodilation), mid → β₁, high → α₁. Use: shock (cardiogenic/septic).', requires:['catecholamine']},
{id:'dobutamine', type:'drug', level:3, char:'Dobutamine', meaning:['β₁ agonist','beta 1 agonist'],
 reading:['cardiogenic shock','inotrope'],
 info:'Predominant β₁ agonist → ↑contractility. Use: cardiogenic shock / acute heart failure.', requires:['catecholamine']},

/* ==================================================================
   LEVEL 4 — Indirect sympathomimetics & sympatholytics (α)
   ================================================================== */
{id:'a2_central', type:'class', level:4, char:'Central α₂ agonists', meaning:['decrease sympathetic outflow','central antihypertensives'],
 info:'Stimulate central α₂ → autoinhibition → ↓sympathetic outflow → ↓BP.', requires:['a2']},
{id:'a_blocker', type:'class', level:4, char:'α-blockers', meaning:['block alpha receptors','vasodilators'],
 reading:['first dose orthostatic hypotension'],
 info:'Block α₁ → vasodilation. Selective α₁ blockers cause less reflex tachycardia (α₂ preserved). ADR: first-dose orthostatic hypotension.', requires:['a1']},

{id:'clonidine', type:'drug', level:4, char:'Clonidine', meaning:['α₂ agonist','central alpha 2 agonist'],
 reading:['hypertension','rebound hypertension on withdrawal'],
 info:'Central α₂ agonist for hypertension; abrupt withdrawal → rebound HTN.', requires:['a2_central']},
{id:'methyldopa', type:'drug', level:4, char:'Methyldopa', meaning:['α₂ agonist','central alpha 2 agonist'],
 reading:['hypertension in pregnancy'],
 info:'Central α₂ agonist — preferred antihypertensive in pregnancy.', requires:['a2_central']},
{id:'prazosin', type:'drug', level:4, char:'Prazosin', meaning:['α₁ blocker','alpha 1 blocker'],
 reading:['first dose hypotension','ptsd nightmares'],
 info:'Selective α₁ blocker. Use: HTN, BPH, PTSD nightmares. ADR: first-dose orthostatic hypotension/syncope.', requires:['a_blocker']},
{id:'tamsulosin', type:'drug', level:4, char:'Tamsulosin', meaning:['α₁ blocker','alpha 1a blocker'],
 reading:['benign prostatic hyperplasia','bph'],
 info:'α₁A-selective → relaxes bladder neck/prostate. Use: BPH; minimal BP effect.', requires:['a_blocker']},
{id:'phenoxybenzamine', type:'drug', level:4, char:'Phenoxybenzamine', meaning:['irreversible α blocker','nonselective alpha blocker'],
 reading:['pheochromocytoma','give before beta blocker'],
 info:'Non-selective IRREVERSIBLE α blocker. Use: pheochromocytoma (α-blockade BEFORE β-blockade).', requires:['a_blocker']},
{id:'amphetamine', type:'drug', level:4, char:'Amphetamine', meaning:['indirect sympathomimetic'],
 reading:['releases norepinephrine','adhd'],
 info:'Indirect sympathomimetic — displaces NE from vesicles + blocks reuptake. CNS stimulant (ADHD, narcolepsy).', requires:['a_blocker']},

/* ==================================================================
   LEVEL 5 — β-blockers
   ================================================================== */
{id:'olol', type:'stem', level:5, char:'-olol', meaning:['beta blocker'],
 mnemonic:'An OLd OWL ("-olol") perches calmly on your heart and slows it down.',
 info:'Suffix marking β-adrenergic antagonists.', requires:[]},
{id:'bblocker', type:'class', level:5, char:'β-blockers', meaning:['decrease heart rate and blood pressure','block beta 1'],
 reading:['mask hypoglycemia','rebound on withdrawal'],
 info:'Block β₁ → ↓HR, ↓contractility, ↓BP, ↓O₂ demand, ↓renin. Uses: HTN, angina, arrhythmia, post-MI, HF, migraine, hyperthyroid tremor. Taper to avoid rebound.', requires:['olol','b1']},
{id:'mixed_blocker', type:'class', level:5, char:'α+β blockers', meaning:['block alpha and beta receptors','mixed adrenergic antagonist'],
 info:'Block both α and β receptors → ↓BP with vasodilation.', requires:['bblocker']},

{id:'propranolol', type:'drug', level:5, char:'Propranolol', meaning:['nonselective β blocker','beta blocker'],
 reading:['migraine prophylaxis','crosses bbb'],
 info:'Non-selective, lipophilic (CNS effects). Use: migraine prophylaxis, hyperthyroidism, performance anxiety. Avoid in asthma.', requires:['bblocker']},
{id:'metoprolol', type:'drug', level:5, char:'Metoprolol', meaning:['cardioselective β₁ blocker','beta 1 selective blocker'],
 reading:['heart failure','post mi'],
 info:'Cardioselective (β₁). Use: HTN, angina, HFrEF (succinate), post-MI.', requires:['bblocker']},
{id:'atenolol', type:'drug', level:5, char:'Atenolol', meaning:['cardioselective β₁ blocker','beta 1 selective blocker'],
 reading:['hypertension','hydrophilic'],
 info:'Cardioselective (β₁), hydrophilic (fewer CNS effects). Use: HTN, angina.', requires:['bblocker']},
{id:'timolol', type:'drug', level:5, char:'Timolol', meaning:['nonselective β blocker','beta blocker'],
 reading:['glaucoma eye drops','reduces aqueous humour'],
 info:'Non-selective β-blocker. Topical use: glaucoma (↓aqueous humour production).', requires:['bblocker']},
{id:'carvedilol', type:'drug', level:5, char:'Carvedilol', meaning:['α and β blocker','alpha and beta blocker'],
 reading:['heart failure','antioxidant'],
 info:'α+β blocker with antioxidant/NO vasodilation. Use: heart failure, HTN.', requires:['mixed_blocker']},
{id:'labetalol', type:'drug', level:5, char:'Labetalol', meaning:['α and β blocker','alpha and beta blocker'],
 reading:['hypertension in pregnancy','pheochromocytoma'],
 info:'α+β blocker. Use: hypertensive emergencies, HTN in pregnancy, pheochromocytoma.', requires:['mixed_blocker']},

/* ==================================================================
   LEVEL 6 — Antibiotic principles & cell-wall agents
   ================================================================== */
{id:'bactericidal', type:'stem', level:6, char:'Bactericidal', meaning:['kills bacteria'],
 mnemonic:'-cidal = homiCIDE: the drug kills the bacteria outright.',
 info:'Kills bacteria directly (cell-wall agents, aminoglycosides, fluoroquinolones, metronidazole).', requires:[]},
{id:'bacteriostatic', type:'stem', level:6, char:'Bacteriostatic', meaning:['inhibits bacterial growth','stops bacterial growth'],
 mnemonic:'-static = STAY still: growth is halted, but host immunity finishes the job.',
 info:'Inhibits growth; relies on host defences (most protein-synthesis inhibitors).', requires:[]},
{id:'betalactam', type:'stem', level:6, char:'β-lactam ring', meaning:['inhibits cell wall synthesis','binds penicillin binding protein','binds pbp'],
 mnemonic:'The β-lactam ring is a fake D-Ala-D-Ala that handcuffs transpeptidase (PBP) → no cross-linking.',
 info:'Core of penicillins, cephalosporins, carbapenems, monobactams. Inhibits transpeptidase (PBP) → blocks peptidoglycan cross-linking.', requires:[]},
{id:'cillin', type:'stem', level:6, char:'-cillin', meaning:['penicillin'],
 mnemonic:'A villain named ciLLIN attacks the bacterial cell wall.',
 info:'Suffix marking penicillin-class antibiotics.', requires:[]},

{id:'penicillins', type:'class', level:6, char:'Penicillins', meaning:['inhibit cell wall synthesis','bind pbp','cell wall synthesis inhibitor'],
 reading:['hypersensitivity','anaphylaxis'],
 info:'β-lactams binding PBPs. Bactericidal. Main ADR: hypersensitivity/anaphylaxis (cross-reactive).', requires:['cillin','betalactam']},
{id:'cephalosporins', type:'class', level:6, char:'Cephalosporins', meaning:['beta lactam cell wall inhibitor','inhibit cell wall synthesis'],
 reading:['generations 1 to 5'],
 info:'β-lactams across 5 generations: 1st = G+ve; broaden to G-ve, Pseudomonas (ceftazidime, cefepime); 5th covers MRSA.', requires:['betalactam']},
{id:'carbapenems', type:'class', level:6, char:'Carbapenems', meaning:['broad spectrum beta lactam','broadest beta lactam'],
 reading:['nosocomial infections','seizure risk'],
 info:'Broadest β-lactams (G+ve, G-ve, anaerobes; not MRSA). Use: serious nosocomial infection. ADR: seizures.', requires:['betalactam']},
{id:'glycopeptides', type:'class', level:6, char:'Glycopeptides', meaning:['bind d-ala-d-ala','inhibit cell wall synthesis'],
 reading:['mrsa','red man syndrome'],
 info:'Bind D-Ala-D-Ala (not PBP) → block cell-wall synthesis. G+ve only. Use: MRSA. ADR: red man syndrome, nephro/ototoxicity.', requires:['bactericidal']},

{id:'amoxicillin', type:'drug', level:6, char:'Amoxicillin', meaning:['aminopenicillin','penicillin'],
 reading:['h pylori','endocarditis prophylaxis'],
 info:'Aminopenicillin (broader G-ve via porins). Food-independent absorption. Use: ENT infections, H. pylori, endocarditis prophylaxis.', requires:['penicillins']},
{id:'cloxacillin', type:'drug', level:6, char:'Cloxacillin', meaning:['antistaphylococcal penicillin','penicillinase resistant penicillin'],
 reading:['s aureus'],
 info:'Penicillinase-resistant penicillin. Use: methicillin-sensitive S. aureus (not MRSA).', requires:['penicillins']},
{id:'piperacillin', type:'drug', level:6, char:'Piperacillin', meaning:['antipseudomonal penicillin'],
 reading:['pseudomonas'],
 info:'Antipseudomonal penicillin (often + tazobactam). Covers Pseudomonas, Klebsiella, Enterobacter.', requires:['penicillins']},
{id:'cefazolin', type:'drug', level:6, char:'Cefazolin', meaning:['1st generation cephalosporin','first generation cephalosporin'],
 reading:['surgical prophylaxis'],
 info:'1st-gen cephalosporin. Use: skin/soft-tissue, surgical prophylaxis.', requires:['cephalosporins']},
{id:'ceftriaxone', type:'drug', level:6, char:'Ceftriaxone', meaning:['3rd generation cephalosporin','third generation cephalosporin'],
 reading:['meningitis','gonorrhea'],
 info:'3rd-gen cephalosporin. Use: community-acquired meningitis, gonorrhoea, pneumonia, pyelonephritis.', requires:['cephalosporins']},
{id:'ceftazidime', type:'drug', level:6, char:'Ceftazidime', meaning:['3rd generation cephalosporin','antipseudomonal cephalosporin'],
 reading:['pseudomonas','melioidosis'],
 info:'3rd-gen, antipseudomonal. Use: HAP, Pseudomonas, and melioidosis (Burkholderia pseudomallei).', requires:['cephalosporins']},
{id:'cefepime', type:'drug', level:6, char:'Cefepime', meaning:['4th generation cephalosporin','fourth generation cephalosporin'],
 reading:['broad spectrum','pseudomonas'],
 info:'4th-gen cephalosporin — broad spectrum incl. Pseudomonas and G+ve.', requires:['cephalosporins']},
{id:'imipenem', type:'drug', level:6, char:'Imipenem', meaning:['carbapenem'],
 reading:['given with cilastatin'],
 info:'Carbapenem inactivated by renal dehydropeptidase-I → combined with cilastatin.', requires:['carbapenems']},
{id:'meropenem', type:'drug', level:6, char:'Meropenem', meaning:['carbapenem'],
 reading:['no cilastatin needed','less seizure risk'],
 info:'Carbapenem stable to renal dehydropeptidase → no cilastatin; lower seizure risk than imipenem.', requires:['carbapenems']},
{id:'vancomycin', type:'drug', level:6, char:'Vancomycin', meaning:['glycopeptide'],
 reading:['mrsa','red man syndrome'],
 info:'Glycopeptide binding D-Ala-D-Ala. Use: MRSA, C. difficile colitis (oral). ADR: red man syndrome, nephro/ototoxicity (TDM).', requires:['glycopeptides']},
{id:'aztreonam', type:'drug', level:6, char:'Aztreonam', meaning:['monobactam'],
 reading:['gram negative only','penicillin allergy'],
 info:'Monobactam — G-ve aerobes only. Low cross-reactivity → option in penicillin allergy.', requires:['betalactam']},

/* ==================================================================
   LEVEL 7 — Protein synthesis inhibitors
   ================================================================== */
{id:'r30s', type:'stem', level:7, char:'30S subunit', meaning:['ribosome target','small ribosomal subunit'],
 mnemonic:'"Buy AT 30, CELL at 50": 30S = Aminoglycosides + Tetracyclines.',
 info:'Bacterial 70S ribosome = 30S + 50S. Drugs binding 30S: aminoglycosides (irreversible→cidal), tetracyclines (reversible→static).', requires:[]},
{id:'r50s', type:'stem', level:7, char:'50S subunit', meaning:['ribosome target','large ribosomal subunit'],
 mnemonic:'CCELL at 50: Chloramphenicol, Clindamycin, Erythromycin (macrolides), Linezolid bind 50S.',
 info:'50S binders: macrolides, lincosamides (clindamycin), chloramphenicol, linezolid → block peptide bond/initiation.', requires:[]},

{id:'aminoglycosides', type:'class', level:7, char:'Aminoglycosides', meaning:['bind 30s irreversibly','bactericidal protein synthesis inhibitor'],
 reading:['nephrotoxicity','ototoxicity'],
 info:'Bind 30S irreversibly → bactericidal; aerobic G-ve only; concentration-dependent + PAE → once-daily. ADR: nephro/ototoxicity.', requires:['r30s','bactericidal']},
{id:'tetracyclines', type:'class', level:7, char:'Tetracyclines', meaning:['bind 30s reversibly','bacteriostatic 30s inhibitor'],
 reading:['tooth discoloration','photosensitivity'],
 info:'Bind 30S reversibly → bacteriostatic; cover atypicals. Chelate cations. Avoid <8y/pregnancy (teeth/bone); photosensitivity.', requires:['r30s','bacteriostatic']},
{id:'macrolides', type:'class', level:7, char:'Macrolides', meaning:['bind 50s','block peptide chain elongation'],
 reading:['qt prolongation','cyp3a4 inhibition'],
 info:'Bind 50S near P site → bacteriostatic; cover G+ve & atypicals. ADR: QT prolongation; ery/clari inhibit CYP3A4.', requires:['r50s']},
{id:'lincosamides', type:'class', level:7, char:'Lincosamides', meaning:['bind 50s like macrolides','50s protein synthesis inhibitor'],
 reading:['c difficile colitis','anaerobes'],
 info:'Bind 50S (same site as macrolides). Cover G+ve cocci & anaerobes. Highest C. difficile colitis risk.', requires:['r50s']},
{id:'amphenicols', type:'class', level:7, char:'Amphenicols', meaning:['bind 50s reversibly','broad spectrum 50s inhibitor'],
 reading:['aplastic anemia','gray baby syndrome'],
 info:'Chloramphenicol — broad-spectrum, bacteriostatic. ADR: aplastic anaemia (idiosyncratic), gray baby syndrome.', requires:['r50s']},
{id:'oxazolidinones', type:'class', level:7, char:'Oxazolidinones', meaning:['bind 23s rrna of 50s','block initiation complex'],
 reading:['gram positive only','serotonin syndrome'],
 info:'Linezolid binds 23S rRNA (unique → no cross-resistance). G+ve only (incl. MRSA/VRE). ADR: thrombocytopenia, serotonin syndrome (MAOI).', requires:['r50s']},

{id:'gentamicin', type:'drug', level:7, char:'Gentamicin', meaning:['aminoglycoside'],
 reading:['gram negative','synergy with beta lactams'],
 info:'Aminoglycoside. G+ve/G-ve incl. Pseudomonas; synergy with cell-wall agents. ADR: nephro/ototoxicity.', requires:['aminoglycosides']},
{id:'amikacin', type:'drug', level:7, char:'Amikacin', meaning:['aminoglycoside'],
 reading:['multidrug resistant gram negative'],
 info:'Aminoglycoside resistant to many inactivating enzymes. Use: MDR G-ve, MDR-TB.', requires:['aminoglycosides']},
{id:'doxycycline', type:'drug', level:7, char:'Doxycycline', meaning:['tetracycline'],
 reading:['atypical infections','non-renal elimination'],
 info:'Tetracycline; non-renal elimination (safe in renal failure). Use: atypicals (Rickettsia, Chlamydia, Mycoplasma), CAP, acne, malaria.', requires:['tetracyclines']},
{id:'tigecycline', type:'drug', level:7, char:'Tigecycline', meaning:['glycylcycline','tetracycline derivative'],
 reading:['evades efflux pumps'],
 info:'Glycylcycline — escapes efflux pumps; broad including MDR organisms. IV only.', requires:['tetracyclines']},
{id:'azithromycin', type:'drug', level:7, char:'Azithromycin', meaning:['macrolide'],
 reading:['long half life','no cyp3a4 effect'],
 info:'Macrolide; t½ ~68h → short courses; no CYP3A4 interaction. Use: CAP, Chlamydia, MAC.', requires:['macrolides']},
{id:'erythromycin', type:'drug', level:7, char:'Erythromycin', meaning:['macrolide'],
 reading:['prokinetic','cyp3a4 inhibitor'],
 info:'Prototype macrolide; CYP3A4 inhibitor; prokinetic (gastroparesis). ADR: GI upset, QT.', requires:['macrolides']},
{id:'clarithromycin', type:'drug', level:7, char:'Clarithromycin', meaning:['macrolide'],
 reading:['h pylori','mac infection'],
 info:'Macrolide; CYP3A4 inhibitor. Use: H. pylori triple therapy, MAC, respiratory infections.', requires:['macrolides']},
{id:'clindamycin', type:'drug', level:7, char:'Clindamycin', meaning:['lincosamide'],
 reading:['anaerobes','c difficile risk'],
 info:'Lincosamide. Use: G+ve & anaerobic infections, community MRSA skin. Highest C. difficile risk.', requires:['lincosamides']},
{id:'chloramphenicol', type:'drug', level:7, char:'Chloramphenicol', meaning:['amphenicol'],
 reading:['gray baby syndrome','aplastic anemia'],
 info:'Broad-spectrum 50S inhibitor. ADR: gray baby syndrome (neonates), aplastic anaemia.', requires:['amphenicols']},
{id:'linezolid', type:'drug', level:7, char:'Linezolid', meaning:['oxazolidinone'],
 reading:['mrsa vre','serotonin syndrome'],
 info:'Oxazolidinone; 100% oral. Use: MRSA, VRE. ADR: thrombocytopenia, serotonin syndrome with SSRIs.', requires:['oxazolidinones']},

/* ==================================================================
   LEVEL 8 — Nucleic-acid & antimetabolite antibiotics
   ================================================================== */
{id:'floxacin', type:'stem', level:8, char:'-floxacin', meaning:['fluoroquinolone'],
 mnemonic:'A FLOCK ("flox") of birds dive-bombs bacterial DNA — fluoroquinolones hit DNA gyrase.',
 info:'Suffix marking fluoroquinolones (inhibit DNA gyrase/topoisomerase IV).', requires:[]},
{id:'folate', type:'stem', level:8, char:'Folate synthesis', meaning:['antibiotic target','bacterial folate pathway'],
 mnemonic:'Bacteria must BUILD their own folate from PABA; we eat ours — so blocking the pathway is selective.',
 info:'Bacteria synthesise folate (PABA→dihydrofolate→THF) for DNA bases. Humans absorb folate → selective toxicity.', requires:[]},

{id:'fluoroquinolones', type:'class', level:8, char:'Fluoroquinolones', meaning:['inhibit dna gyrase','inhibit topoisomerase'],
 reading:['tendon rupture','qt prolongation'],
 info:'Inhibit DNA gyrase (topo II) & topo IV. Broad-spectrum. ADR: tendinitis/rupture, QT prolongation; avoid <18y/pregnancy.', requires:['floxacin']},
{id:'folate_inhibitors', type:'class', level:8, char:'Folate synthesis inhibitors', meaning:['block folate pathway','antifolate antibiotics'],
 reading:['sequential blockade synergy'],
 info:'Sulfonamides (block dihydropteroate synthase) + trimethoprim (block dihydrofolate reductase) → sequential blockade = synergy.', requires:['folate']},
{id:'nitroimidazoles', type:'class', level:8, char:'Nitroimidazoles', meaning:['free radical dna damage','anaerobe and protozoa killer'],
 reading:['disulfiram reaction with alcohol'],
 info:'Form cytotoxic free radicals in anaerobic conditions → kill anaerobes & protozoa. ADR: disulfiram-like reaction with alcohol.', requires:['bactericidal']},

{id:'ciprofloxacin', type:'drug', level:8, char:'Ciprofloxacin', meaning:['fluoroquinolone'],
 reading:['gram negative','pseudomonas'],
 info:'Fluoroquinolone (2nd gen). Use: UTI, GI infections, Pseudomonas. Chelated by cations.', requires:['fluoroquinolones']},
{id:'levofloxacin', type:'drug', level:8, char:'Levofloxacin', meaning:['respiratory fluoroquinolone','fluoroquinolone'],
 reading:['community acquired pneumonia','atypicals'],
 info:'Respiratory fluoroquinolone. Use: CAP, atypical pneumonia (Mycoplasma, Chlamydia).', requires:['fluoroquinolones']},
{id:'moxifloxacin', type:'drug', level:8, char:'Moxifloxacin', meaning:['respiratory fluoroquinolone','fluoroquinolone'],
 reading:['broadest spectrum','qt prolongation'],
 info:'Broadest fluoroquinolone (+anaerobes). Notable QTc prolongation → torsades risk.', requires:['fluoroquinolones']},
{id:'sulfamethoxazole', type:'drug', level:8, char:'Sulfamethoxazole', meaning:['sulfonamide'],
 reading:['blocks dihydropteroate synthase','g6pd hemolysis'],
 info:'Sulfonamide → inhibits dihydropteroate synthase. ADR: rash/SJS, hemolysis in G6PD deficiency, kernicterus (<2mo).', requires:['folate_inhibitors']},
{id:'trimethoprim', type:'drug', level:8, char:'Trimethoprim', meaning:['dihydrofolate reductase inhibitor','dhfr inhibitor'],
 reading:['megaloblastic anemia','rescued by folinic acid'],
 info:'Inhibits bacterial DHFR. ADR: folate-deficiency anaemia (give folinic acid).', requires:['folate_inhibitors']},
{id:'cotrimoxazole', type:'drug', level:8, char:'Co-trimoxazole', meaning:['sulfamethoxazole plus trimethoprim','antifolate combination'],
 reading:['pcp prophylaxis','uti'],
 info:'SMX + TMP (5:1) = sequential folate blockade. Use: UTI, PCP (Pneumocystis), toxoplasmosis.', requires:['folate_inhibitors']},
{id:'metronidazole', type:'drug', level:8, char:'Metronidazole', meaning:['nitroimidazole'],
 reading:['anaerobes and protozoa','disulfiram reaction'],
 info:'Nitroimidazole. Use: anaerobes, C. difficile, amoebiasis, giardiasis, trichomoniasis. ADR: disulfiram-like reaction.', requires:['nitroimidazoles']},

/* ==================================================================
   LEVEL 9 — Antifungals
   ================================================================== */
{id:'ergosterol', type:'stem', level:9, char:'Ergosterol', meaning:['fungal membrane sterol','antifungal target'],
 mnemonic:'Ergosterol is the fungal cholesterol — the membrane Achilles’ heel that polyenes and azoles attack.',
 info:'Fungal cell-membrane sterol. Polyenes bind it (pores); azoles/allylamines block its synthesis.', requires:[]},
{id:'azole_stem', type:'stem', level:9, char:'-azole / -conazole', meaning:['azole antifungal'],
 mnemonic:'PRAY ("-azole") that the fungus stops growing — azoles block ergosterol synthesis (fungistatic).',
 info:'Suffix marking azole antifungals — inhibit 14-α-demethylase (CYP51).', requires:[]},
{id:'glucan', type:'stem', level:9, char:'β-1,3-D-glucan', meaning:['fungal cell wall component','echinocandin target'],
 mnemonic:'Glucan is the fungal brick wall — echinocandins are the wrecking ball (humans have no glucan).',
 info:'Fungal cell-wall polysaccharide; target of echinocandins (no human equivalent → very safe).', requires:[]},

{id:'polyenes', type:'class', level:9, char:'Polyenes', meaning:['bind ergosterol','form membrane pores'],
 reading:['nephrotoxicity','infusion reactions'],
 info:'Bind ergosterol → membrane pores → ion leakage. Amphotericin B = broadest. ADR: nephrotoxicity, infusion reactions.', requires:['ergosterol']},
{id:'azoles', type:'class', level:9, char:'Azoles', meaning:['inhibit ergosterol synthesis','inhibit 14 alpha demethylase'],
 reading:['hepatotoxicity','cyp interactions'],
 info:'Inhibit 14-α-demethylase (CYP51) → ↓ergosterol → fungistatic. ADR: hepatotoxicity, CYP drug interactions.', requires:['ergosterol','azole_stem']},
{id:'echinocandins', type:'class', level:9, char:'Echinocandins', meaning:['inhibit glucan synthase','inhibit fungal cell wall'],
 reading:['candidemia first line','iv only'],
 info:'Inhibit β-1,3-D-glucan synthase → disrupt cell wall. IV only; Candida & Aspergillus. First-line candidemia. Very few ADRs.', requires:['glucan']},
{id:'allylamines', type:'class', level:9, char:'Allylamines', meaning:['inhibit squalene epoxidase','block ergosterol synthesis'],
 reading:['onychomycosis'],
 info:'Inhibit squalene epoxidase → toxic squalene buildup → fungicidal. Keratophilic. Best for onychomycosis.', requires:['ergosterol']},

{id:'amphotericin', type:'drug', level:9, char:'Amphotericin B', meaning:['polyene'],
 reading:['broadest spectrum','nephrotoxic'],
 info:'Polyene; broadest antifungal; IV; t½ ~15 days. Use: severe systemic mycoses. ADR: nephrotoxicity, infusion fever.', requires:['polyenes']},
{id:'nystatin', type:'drug', level:9, char:'Nystatin', meaning:['polyene'],
 reading:['topical only','oral thrush'],
 info:'Polyene, topical only (too toxic IV). Use: oral/vaginal/cutaneous candidiasis.', requires:['polyenes']},
{id:'fluconazole', type:'drug', level:9, char:'Fluconazole', meaning:['azole','triazole'],
 reading:['best csf penetration','no aspergillus coverage'],
 info:'Triazole; best CSF penetration. Use: candidiasis, cryptococcal meningitis maintenance. No Aspergillus activity.', requires:['azoles']},
{id:'voriconazole', type:'drug', level:9, char:'Voriconazole', meaning:['azole','triazole'],
 reading:['aspergillosis','visual disturbances'],
 info:'Triazole; drug of choice for invasive aspergillosis. ADR: visual disturbances (~30%), photosensitivity.', requires:['azoles']},
{id:'itraconazole', type:'drug', level:9, char:'Itraconazole', meaning:['azole','triazole'],
 reading:['dimorphic fungi'],
 info:'Triazole; azole of choice for dimorphic fungi (Histoplasma, Blastomyces, Sporothrix). Keratophilic. Poor CSF.', requires:['azoles']},
{id:'ketoconazole', type:'drug', level:9, char:'Ketoconazole', meaning:['azole','imidazole'],
 reading:['cyp3a4 inhibitor','anti androgen effects'],
 info:'Imidazole; strong CYP3A4 inhibitor; inhibits steroid synthesis → gynecomastia, ↓libido. Largely superseded.', requires:['azoles']},
{id:'caspofungin', type:'drug', level:9, char:'Caspofungin', meaning:['echinocandin'],
 reading:['candidemia','iv only'],
 info:'Echinocandin, IV. Use: esophageal candidiasis, candidemia, BMT prophylaxis.', requires:['echinocandins']},
{id:'terbinafine', type:'drug', level:9, char:'Terbinafine', meaning:['allylamine'],
 reading:['onychomycosis','best for nail infection'],
 info:'Allylamine; best oral agent for onychomycosis & dermatophytosis. Few CYP interactions.', requires:['allylamines']},
{id:'flucytosine', type:'drug', level:9, char:'Flucytosine (5-FC)', meaning:['pyrimidine analog antifungal'],
 reading:['synergy with amphotericin','bone marrow toxicity'],
 info:'Pyrimidine analog → 5-FU intracellularly. Synergistic with amphotericin B (cryptococcal meningitis). ADR: marrow toxicity.', requires:['polyenes']},
{id:'griseofulvin', type:'drug', level:9, char:'Griseofulvin', meaning:['microtubule inhibitor antifungal'],
 reading:['dermatophytes only'],
 info:'Inhibits fungal microtubules → fungistatic; dermatophytes only. Largely replaced by terbinafine/itraconazole.', requires:['allylamines']},

/* ==================================================================
   LEVEL 10 — Antivirals: herpes, CMV, HBV
   ================================================================== */
{id:'nucleoside', type:'stem', level:10, char:'Nucleoside analog', meaning:['chain terminator','inhibits viral polymerase'],
 mnemonic:'A fake nucleotide with no 3′-OH = a dead-end brick: the growing viral DNA/RNA chain stops.',
 info:'Mimics a nucleotide; lacks 3′-OH → chain termination of viral polymerase/RT. Backbone of antiviral therapy.', requires:[]},
{id:'viral_tk', type:'stem', level:10, char:'Viral thymidine kinase', meaning:['activates acyclovir','phosphorylates acyclovir'],
 mnemonic:'Acyclovir is a sleeping prodrug; only the virus’s OWN thymidine kinase wakes it up → selectivity.',
 info:'Herpes viral TK performs the first phosphorylation of acyclovir → activation only in infected cells (selectivity).', requires:[]},

{id:'anti_herpes', type:'class', level:10, char:'Anti-herpes agents', meaning:['inhibit viral dna polymerase','herpes dna polymerase inhibitor'],
 info:'Guanosine analogs activated by viral TK → inhibit HSV/VZV DNA polymerase (chain termination).', requires:['nucleoside','viral_tk']},
{id:'anti_cmv', type:'class', level:10, char:'Anti-CMV agents', meaning:['inhibit cmv dna polymerase'],
 reading:['bone marrow toxicity'],
 info:'Treat CMV (retinitis, transplant). Ganciclovir activated by UL97 kinase. ADR: marrow suppression.', requires:['nucleoside']},
{id:'hbv_drugs', type:'class', level:10, char:'Anti-HBV agents', meaning:['inhibit reverse transcriptase','hbv polymerase inhibitor'],
 info:'Nucleos(t)ide analogs inhibiting HBV reverse transcriptase (HBV replicates via RT). First-line: entecavir, tenofovir.', requires:['nucleoside']},

{id:'acyclovir', type:'drug', level:10, char:'Acyclovir', meaning:['anti-herpes nucleoside analog','herpes dna polymerase inhibitor'],
 reading:['activated by viral tk','hsv vzv'],
 info:'Guanosine analog; activated by viral TK; chain terminator. Use: HSV-1/2, VZV. Low oral bioavailability (10–20%).', requires:['anti_herpes']},
{id:'valacyclovir', type:'drug', level:10, char:'Valacyclovir', meaning:['acyclovir prodrug'],
 reading:['better oral bioavailability'],
 info:'L-valyl ester prodrug of acyclovir → higher oral bioavailability (54–70%), BID dosing.', requires:['anti_herpes']},
{id:'ganciclovir', type:'drug', level:10, char:'Ganciclovir', meaning:['anti-cmv agent'],
 reading:['activated by ul97 kinase','bone marrow toxicity'],
 info:'Guanine analog activated by CMV UL97 kinase. Use: CMV retinitis, transplant prophylaxis. ADR: neutropenia/thrombocytopenia.', requires:['anti_cmv']},
{id:'valganciclovir', type:'drug', level:10, char:'Valganciclovir', meaning:['ganciclovir prodrug'],
 reading:['oral cmv maintenance'],
 info:'Oral L-valyl ester prodrug of ganciclovir; replaces IV GCV for maintenance.', requires:['anti_cmv']},
{id:'cidofovir', type:'drug', level:10, char:'Cidofovir', meaning:['anti-cmv agent','cytidine nucleotide analog'],
 reading:['cellular activation','nephrotoxic give probenecid'],
 info:'Activated by cellular enzymes (works in UL97-mutant GCV-resistant CMV). ADR: nephrotoxicity → give probenecid.', requires:['anti_cmv']},
{id:'entecavir', type:'drug', level:10, char:'Entecavir', meaning:['anti-hbv nucleoside analog'],
 reading:['first line hbv','low resistance'],
 info:'Potent first-line HBV nucleoside analog; low resistance.', requires:['hbv_drugs']},
{id:'tenofovir', type:'drug', level:10, char:'Tenofovir', meaning:['anti-hbv nucleotide analog'],
 reading:['first line hbv','hbv hiv coinfection'],
 info:'Nucleotide analog; first-line HBV, very low resistance; useful in HBV/HIV co-infection.', requires:['hbv_drugs']},

/* ==================================================================
   LEVEL 11 — Antivirals: HCV, influenza, COVID-19
   ================================================================== */
{id:'previr', type:'stem', level:11, char:'-previr', meaning:['ns3 4a protease inhibitor','hcv protease inhibitor'],
 mnemonic:'"-previr" PREVents the protein-cutting — it blocks the HCV NS3/4A protease.',
 info:'Suffix: HCV NS3/4A serine protease inhibitors (block polyprotein processing).', requires:[]},
{id:'asvir', type:'stem', level:11, char:'-asvir', meaning:['ns5a inhibitor','hcv ns5a inhibitor'],
 mnemonic:'"-Asvir" = NS5A — block the A protein that runs replication & assembly.',
 info:'Suffix: HCV NS5A inhibitors (block RNA replication & assembly).', requires:[]},
{id:'buvir', type:'stem', level:11, char:'-buvir', meaning:['ns5b polymerase inhibitor','rdrp inhibitor'],
 mnemonic:'"-Buvir" = NS5B — block the polymerase Building the viral RNA.',
 info:'Suffix: HCV NS5B RNA-dependent RNA polymerase inhibitors. Sofosbuvir is the backbone.', requires:[]},
{id:'neuraminidase', type:'stem', level:11, char:'Neuraminidase', meaning:['influenza release enzyme','antiviral target'],
 mnemonic:'Neuraminidase is the scissors that lets new flu virions escape — block it and they’re stuck.',
 info:'Influenza surface enzyme enabling viral budding/release; target of oseltamivir/zanamivir.', requires:[]},

{id:'daa', type:'class', level:11, char:'HCV direct-acting antivirals', meaning:['cure hepatitis c','direct acting antivirals'],
 reading:['cure rate over 95 percent'],
 info:'Combinations of NS3/4A (-previr), NS5A (-asvir), NS5B (-buvir) inhibitors → HCV cure >95%. Never monotherapy.', requires:['asvir','buvir']},
{id:'neuraminidase_inh', type:'class', level:11, char:'Neuraminidase inhibitors', meaning:['block influenza release','inhibit neuraminidase'],
 reading:['start within 48 hours','influenza a and b'],
 info:'Inhibit influenza neuraminidase → ↓viral release. Cover influenza A & B; start within 48h of onset.', requires:['neuraminidase']},
{id:'covid_av', type:'class', level:11, char:'COVID-19 antivirals', meaning:['inhibit sars cov 2 replication'],
 info:'Target SARS-CoV-2 RNA replication (RdRp inhibitors or lethal mutagenesis).', requires:['nucleoside']},

{id:'sofosbuvir', type:'drug', level:11, char:'Sofosbuvir', meaning:['ns5b inhibitor','hcv polymerase inhibitor'],
 reading:['backbone of hcv regimens'],
 info:'NS5B (-buvir) polymerase inhibitor — backbone of modern HCV regimens (e.g. with velpatasvir/ledipasvir).', requires:['daa']},
{id:'ledipasvir', type:'drug', level:11, char:'Ledipasvir', meaning:['ns5a inhibitor'],
 reading:['combined with sofosbuvir'],
 info:'NS5A (-asvir) inhibitor; combined with sofosbuvir (Harvoni) for genotype 1 HCV.', requires:['daa']},
{id:'grazoprevir', type:'drug', level:11, char:'Grazoprevir', meaning:['ns3 4a protease inhibitor'],
 reading:['hcv protease inhibitor'],
 info:'NS3/4A (-previr) protease inhibitor; used in combination HCV regimens.', requires:['previr']},
{id:'oseltamivir', type:'drug', level:11, char:'Oseltamivir', meaning:['neuraminidase inhibitor'],
 reading:['oral','influenza a and b'],
 info:'Oral neuraminidase inhibitor (Tamiflu). Influenza A & B; start ≤48h. ADR: nausea/vomiting.', requires:['neuraminidase_inh']},
{id:'zanamivir', type:'drug', level:11, char:'Zanamivir', meaning:['neuraminidase inhibitor'],
 reading:['inhaled','avoid in asthma'],
 info:'Inhaled neuraminidase inhibitor. ADR: bronchospasm → avoid in asthma/COPD.', requires:['neuraminidase_inh']},
{id:'remdesivir', type:'drug', level:11, char:'Remdesivir', meaning:['rdrp inhibitor'],
 reading:['iv','hospitalized covid on oxygen'],
 info:'Adenosine analog → RdRp chain termination. IV. Use: hospitalised COVID needing supplemental O₂ (not on ventilator).', requires:['covid_av']},
{id:'molnupiravir', type:'drug', level:11, char:'Molnupiravir', meaning:['lethal mutagenesis agent'],
 reading:['oral covid','avoid in pregnancy'],
 info:'NHC prodrug → incorporated into viral RNA → lethal mutagenesis. Oral, early high-risk COVID. Avoid in pregnancy.', requires:['covid_av']},
{id:'favipiravir', type:'drug', level:11, char:'Favipiravir', meaning:['rdrp inhibitor'],
 reading:['oral','originally for influenza'],
 info:'Pyrazine carboxamide → RdRp inhibitor; developed for influenza, repurposed for COVID-19. Oral.', requires:['covid_av']},

/* ==================================================================
   LEVEL 12 — Oncology: cytotoxic chemotherapy
   ================================================================== */
{id:'ccs', type:'stem', level:12, char:'Cell cycle-specific (CCS)', meaning:['kills dividing cells','phase specific'],
 mnemonic:'CCS only hits cells "in motion" — great for fast tumours (leukemia), useless on resting G₀ cells.',
 info:'Active in a specific cell-cycle phase; best for high-growth-fraction tumours (leukemia). Ineffective on G₀.', requires:[]},
{id:'ccns', type:'stem', level:12, char:'Cell cycle-nonspecific (CCNS)', meaning:['kills resting and dividing cells','phase nonspecific'],
 mnemonic:'CCNS hits cells whether they’re moving or napping — works on slow tumours (breast, prostate) too.',
 info:'Kill cycling and resting (G₀) cells; useful in low-growth-fraction tumours (breast, prostate). Alkylating agents, anthracyclines.', requires:[]},

{id:'alkylating', type:'class', level:12, char:'Alkylating agents', meaning:['dna cross-linking','cross-link dna'],
 reading:['myelosuppression','secondary malignancy'],
 info:'Covalently cross-link DNA (guanine N-7). CCNS. ADR: myelosuppression, secondary AML.', requires:['ccns']},
{id:'antimetabolites', type:'class', level:12, char:'Antimetabolites', meaning:['inhibit dna synthesis','s phase specific'],
 reading:['mucositis','myelosuppression'],
 info:'Fake building blocks blocking DNA/RNA synthesis (S-phase, CCS). Folate/purine/pyrimidine analogs.', requires:['ccs']},
{id:'anthracyclines', type:'class', level:12, char:'Anthracyclines', meaning:['inhibit topoisomerase ii','dna intercalation'],
 reading:['cardiotoxicity','dexrazoxane protects'],
 info:'Intercalate DNA + inhibit topoisomerase II + free radicals. CCNS. ADR: cardiotoxicity → dexrazoxane.', requires:['ccns']},
{id:'vinca', type:'class', level:12, char:'Vinca alkaloids', meaning:['inhibit microtubule polymerization','m phase blocker'],
 reading:['metaphase arrest'],
 info:'Bind β-tubulin → block microtubule polymerisation → M-phase (metaphase) arrest. IV only.', requires:['ccs']},
{id:'taxanes', type:'class', level:12, char:'Taxanes', meaning:['stabilize microtubules','prevent microtubule depolymerization'],
 reading:['hypersensitivity'],
 info:'Hyper-stabilise microtubules → block depolymerisation → metaphase arrest (opposite of vinca). ADR: hypersensitivity, neuropathy.', requires:['ccs']},

{id:'cyclophosphamide', type:'drug', level:12, char:'Cyclophosphamide', meaning:['alkylating agent'],
 reading:['hemorrhagic cystitis','mesna protects'],
 info:'Prodrug → phosphoramide mustard (active) + acrolein (toxic). ADR: hemorrhagic cystitis → hydration + MESNA.', requires:['alkylating']},
{id:'methotrexate', type:'drug', level:12, char:'Methotrexate', meaning:['antimetabolite','folate analog'],
 reading:['inhibits dihydrofolate reductase','leucovorin rescue'],
 info:'Folate analog → irreversibly inhibits DHFR → "thymineless death". Rescue normal cells with leucovorin.', requires:['antimetabolites']},
{id:'fluorouracil', type:'drug', level:12, char:'5-Fluorouracil', meaning:['antimetabolite','pyrimidine analog'],
 reading:['inhibits thymidylate synthase','hand foot syndrome'],
 info:'Pyrimidine analog → F-dUMP inhibits thymidylate synthase. DPD deficiency → ↑toxicity. ADR: hand-foot syndrome, mucositis.', requires:['antimetabolites']},
{id:'mercaptopurine', type:'drug', level:12, char:'6-Mercaptopurine', meaning:['antimetabolite','purine analog'],
 reading:['allopurinol interaction','tpmt deficiency'],
 info:'Purine analog. Inactivated by xanthine oxidase → allopurinol ↑levels (reduce dose). TPMT deficiency → myelosuppression.', requires:['antimetabolites']},
{id:'doxorubicin', type:'drug', level:12, char:'Doxorubicin', meaning:['anthracycline'],
 reading:['cardiotoxicity','free radical damage'],
 info:'Anthracycline (topo II inhibitor + free radicals). ADR: dose-dependent cardiotoxicity → dexrazoxane; vesicant; red urine.', requires:['anthracyclines']},
{id:'bleomycin', type:'drug', level:12, char:'Bleomycin', meaning:['cytotoxic antibiotic'],
 reading:['pulmonary fibrosis','g2 phase specific'],
 info:'Free-radical DNA scission (G₂/M). ADR: interstitial pneumonitis/pulmonary fibrosis; minimal myelosuppression.', requires:['ccs']},
{id:'vincristine', type:'drug', level:12, char:'Vincristine', meaning:['vinca alkaloid'],
 reading:['peripheral neuropathy'],
 info:'Vinca alkaloid. ADR: peripheral neuropathy (VIPN), constipation/ileus. Minimal marrow toxicity.', requires:['vinca']},
{id:'vinblastine', type:'drug', level:12, char:'Vinblastine', meaning:['vinca alkaloid'],
 reading:['myelosuppression'],
 info:'Vinca alkaloid. ADR: myelosuppression (the "blast" hits the bone marrow).', requires:['vinca']},
{id:'paclitaxel', type:'drug', level:12, char:'Paclitaxel', meaning:['taxane'],
 reading:['ovarian and breast cancer'],
 info:'Taxane → stabilises microtubules. Use: ovarian, breast cancer. ADR: hypersensitivity, neuropathy, neutropenia.', requires:['taxanes']},

/* ==================================================================
   LEVEL 13 — Oncology: targeted & hormonal therapy
   ================================================================== */
{id:'er_pr', type:'stem', level:13, char:'ER / PR', meaning:['hormone receptor','breast cancer hormone receptor'],
 mnemonic:'ER/PR-positive tumours are "fed" by estrogen — starve them and they shrink.',
 info:'Estrogen/progesterone receptors; positive in ~30% of breast cancers → targetable by hormonal therapy.', requires:[]},
{id:'tinib', type:'stem', level:13, char:'-tinib', meaning:['tyrosine kinase inhibitor'],
 mnemonic:'"-tinib" = Tyrosine kINase Inhibitor Blocker — small oral molecules.',
 info:'Suffix: small-molecule tyrosine kinase inhibitors (oral, t½ 12–24h).', requires:[]},
{id:'mab', type:'stem', level:13, char:'-mab', meaning:['monoclonal antibody'],
 mnemonic:'"-mab" = Monoclonal AntiBody — large IV proteins targeting tumour surface markers.',
 info:'Suffix: monoclonal antibodies (IV, days–weeks half-life) against tumour surface proteins.', requires:[]},

{id:'serm', type:'class', level:13, char:'SERMs', meaning:['estrogen receptor modulators','selective estrogen receptor modulators'],
 reading:['breast antagonist uterus agonist'],
 info:'Selective estrogen-receptor modulators — antagonist in breast, agonist in uterus/bone.', requires:['er_pr']},
{id:'aromatase_inh', type:'class', level:13, char:'Aromatase inhibitors', meaning:['block estrogen synthesis','inhibit aromatase'],
 reading:['postmenopausal only','osteoporosis risk'],
 info:'Inhibit aromatase (CYP19) → ↓estrogen synthesis. Postmenopausal only. ADR: osteoporosis, arthralgia.', requires:['er_pr']},
{id:'tki', type:'class', level:13, char:'Tyrosine kinase inhibitors', meaning:['block tyrosine kinase signaling','inhibit tyrosine kinase'],
 reading:['oral small molecules'],
 info:'Small oral molecules blocking ATP binding at tyrosine-kinase domains of oncogenic receptors.', requires:['tinib']},
{id:'mab_cancer', type:'class', level:13, char:'Monoclonal antibodies', meaning:['target tumor surface proteins','antibody therapy'],
 reading:['infusion reactions'],
 info:'IV antibodies against tumour surface antigens (HER2, EGFR, VEGF) → block signalling + immune killing (ADCC/CDC).', requires:['mab']},

{id:'tamoxifen', type:'drug', level:13, char:'Tamoxifen', meaning:['serm'],
 reading:['endometrial cancer risk','cyp2d6 to endoxifen'],
 info:'SERM (CYP2D6 → endoxifen). Use: ER+/PR+ breast cancer (pre- and post-menopause). ADR: endometrial CA, DVT; ↑bone density.', requires:['serm']},
{id:'anastrozole', type:'drug', level:13, char:'Anastrozole', meaning:['aromatase inhibitor'],
 reading:['nonsteroidal reversible','postmenopausal'],
 info:'Non-steroidal reversible aromatase inhibitor. Use: postmenopausal ER+ breast cancer.', requires:['aromatase_inh']},
{id:'letrozole', type:'drug', level:13, char:'Letrozole', meaning:['aromatase inhibitor'],
 reading:['nonsteroidal reversible','postmenopausal'],
 info:'Non-steroidal reversible aromatase inhibitor. Use: postmenopausal ER+ breast cancer.', requires:['aromatase_inh']},
{id:'imatinib', type:'drug', level:13, char:'Imatinib', meaning:['tyrosine kinase inhibitor','bcr abl inhibitor'],
 reading:['cml philadelphia chromosome','gist'],
 info:'BCR-ABL TKI (Philadelphia chromosome). Use: CML, GIST (c-KIT). Metabolised by CYP3A4.', requires:['tki']},
{id:'gefitinib', type:'drug', level:13, char:'Gefitinib', meaning:['egfr tyrosine kinase inhibitor','tyrosine kinase inhibitor'],
 reading:['nsclc with egfr mutation','acneiform rash'],
 info:'EGFR TKI. Use: NSCLC with EGFR activating mutation. ADR: acneiform rash (correlates with efficacy), diarrhoea.', requires:['tki']},
{id:'trastuzumab', type:'drug', level:13, char:'Trastuzumab', meaning:['anti-her2 monoclonal antibody','monoclonal antibody'],
 reading:['her2 positive breast cancer','cardiotoxicity'],
 info:'Anti-HER2 mAb. Use: HER2+ breast cancer. ADR: cardiotoxicity, infusion reactions.', requires:['mab_cancer']},
{id:'bevacizumab', type:'drug', level:13, char:'Bevacizumab', meaning:['anti-vegf monoclonal antibody','monoclonal antibody'],
 reading:['inhibits angiogenesis','bleeding gi perforation'],
 info:'Anti-VEGF mAb → inhibits angiogenesis. Use: metastatic CRC, NSCLC. ADR: bleeding, GI perforation, poor wound healing.', requires:['mab_cancer']},
{id:'cetuximab', type:'drug', level:13, char:'Cetuximab', meaning:['anti-egfr monoclonal antibody','monoclonal antibody'],
 reading:['colorectal cancer kras wild type','acneiform rash'],
 info:'Anti-EGFR mAb. Use: metastatic CRC with KRAS wild-type (KRAS-mutant → no response). ADR: acneiform rash.', requires:['mab_cancer']},

/* ==================================================================
   ADDED TOPICS — remaining high-yield items from the database notes
   ================================================================== */

/* ---- Level 2 (Cholinergic): more agonists, AChE inhibitors, antimuscarinics, nicotinic ---- */
{id:'nic_agonist', type:'class', level:2, char:'Nicotinic agonists', meaning:['activate nicotinic receptors'],
 reading:['smoking cessation'],
 info:'Agonists at nicotinic receptors. Uses: smoking cessation (nicotine, varenicline). Prolonged stimulation causes desensitization/depolarizing block.', requires:['nicotinic']},
{id:'carbachol', type:'drug', level:2, char:'Carbachol', meaning:['muscarinic agonist'],
 reading:['glaucoma surgery (topical)'],
 info:'AChE-resistant choline ester with muscarinic + nicotinic activity. Topical use: miotic in glaucoma/eye surgery.', requires:['musc_agonist']},
{id:'methacholine', type:'drug', level:2, char:'Methacholine', meaning:['muscarinic agonist'],
 reading:['asthma challenge test'],
 info:'Muscarinic-selective, AChE-resistant. Use: methacholine challenge test (bronchial hyperreactivity / asthma diagnosis).', requires:['musc_agonist']},
{id:'cevimeline', type:'drug', level:2, char:'Cevimeline', meaning:['muscarinic agonist'],
 reading:['xerostomia in Sjogren syndrome'],
 info:'M1/M3-selective agonist. Use: xerostomia in Sjogren syndrome; fewer CNS effects than pilocarpine.', requires:['musc_agonist']},
{id:'edrophonium', type:'drug', level:2, char:'Edrophonium', meaning:['ache inhibitor','acetylcholinesterase inhibitor'],
 reading:['Tensilon test for myasthenia gravis'],
 info:'Short-acting AChE inhibitor (5-15 min). Use: Tensilon test to diagnose myasthenia gravis.', requires:['ache_inh']},
{id:'pyridostigmine', type:'drug', level:2, char:'Pyridostigmine', meaning:['ache inhibitor','acetylcholinesterase inhibitor'],
 reading:['myasthenia gravis maintenance'],
 info:'Quaternary carbamate (no BBB), longer-acting than neostigmine. Use: chronic myasthenia gravis treatment.', requires:['ache_inh']},
{id:'rivastigmine', type:'drug', level:2, char:'Rivastigmine', meaning:['ache inhibitor','acetylcholinesterase inhibitor'],
 reading:['Alzheimer and Parkinson dementia'],
 info:'Central AChE inhibitor. Use: Alzheimer disease and Parkinson disease dementia.', requires:['ache_inh']},
{id:'botulinum', type:'drug', level:2, char:'Botulinum toxin', meaning:['blocks acetylcholine release'],
 reading:['cleaves SNARE (SNAP-25)'],
 info:'Protease that cleaves SNARE (SNAP-25) -> blocks ACh release -> reversible flaccid paralysis (~3-4 months). Uses: dystonia, spasticity, hyperhidrosis, migraine, cosmetic.', requires:['ach']},
{id:'scopolamine', type:'drug', level:2, char:'Scopolamine', meaning:['muscarinic antagonist','anticholinergic'],
 reading:['motion sickness'],
 info:'Antimuscarinic with high CNS penetration. Use: motion sickness, vertigo.', requires:['musc_antag']},
{id:'oxybutynin', type:'drug', level:2, char:'Oxybutynin', meaning:['muscarinic antagonist','anticholinergic'],
 reading:['overactive bladder'],
 info:'Bladder-selective antimuscarinic. Use: overactive bladder, urge incontinence.', requires:['musc_antag']},
{id:'benztropine', type:'drug', level:2, char:'Benztropine', meaning:['muscarinic antagonist','anticholinergic'],
 reading:['Parkinson tremor'],
 info:'Central antimuscarinic. Use: Parkinson disease (reduces tremor); also drug-induced extrapyramidal symptoms.', requires:['musc_antag']},
{id:'nicotine_drug', type:'drug', level:2, char:'Nicotine', meaning:['nicotinic agonist'],
 reading:['smoking cessation (patch/gum)'],
 info:'Nicotinic agonist (NN>NM). Use: smoking cessation (patch, gum).', requires:['nic_agonist']},
{id:'varenicline', type:'drug', level:2, char:'Varenicline', meaning:['partial nicotinic agonist'],
 reading:['smoking cessation'],
 info:'Partial agonist at alpha4beta2 nicotinic receptor. Use: smoking cessation.', requires:['nic_agonist']},
{id:'atracurium', type:'drug', level:2, char:'Atracurium', meaning:['nondepolarizing neuromuscular blocker'],
 reading:['Hofmann elimination'],
 info:'Non-depolarizing NM blocker cleared by Hofmann elimination (no liver/kidney needed). Surgical relaxant.', requires:['nmj_blocker']},

/* ---- Level 3 (Adrenergic): D1, beta3, more agonists ---- */
{id:'d1', type:'stem', level:3, char:'D-1 receptor', meaning:['renal vasodilation'],
 mnemonic:'D-ONE opens the renal floodgates: D1 dilates kidney vessels to boost renal blood flow.',
 info:'Dopamine D1 receptor: vasodilation of renal/mesenteric vasculature -> increased renal blood flow (low-dose dopamine).', requires:[]},
{id:'b3', type:'stem', level:3, char:'beta-3 receptor', meaning:['bladder relaxation','lipolysis'],
 mnemonic:'beta-THREE = Bladder + Belly fat: relaxes the bladder and burns fat (lipolysis).',
 info:'beta-3 adrenoceptor (Gs): detrusor (bladder) relaxation and lipolysis in adipose tissue.', requires:[]},
{id:'isoproterenol', type:'drug', level:3, char:'Isoproterenol', meaning:['nonselective beta agonist'],
 reading:['increases heart rate; reflex tachycardia'],
 info:'Nonselective beta1=beta2 agonist. Effects: increased HR/contractility, vasodilation (lower diastolic BP) -> reflex tachycardia. Cardiac stimulant.', requires:['catecholamine']},
{id:'terbutaline', type:'drug', level:3, char:'Terbutaline', meaning:['beta 2 agonist'],
 reading:['asthma and tocolysis'],
 info:'Short-acting beta2 agonist. Use: acute asthma and premature labour (tocolysis).', requires:['b2_agonist']},
{id:'oxymetazoline', type:'drug', level:3, char:'Oxymetazoline', meaning:['alpha 1 agonist'],
 reading:['topical nasal decongestant'],
 info:'Topical alpha agonist. Use: nasal decongestant; rebound congestion with overuse.', requires:['a1_agonist']},
{id:'mirabegron', type:'drug', level:3, char:'Mirabegron', meaning:['beta 3 agonist'],
 reading:['overactive bladder'],
 info:'beta-3 agonist -> relaxes detrusor. Use: overactive bladder.', requires:['b3']},

/* ---- Level 4 (Sympatholytics/indirect): neuron blockers, more alpha agents ---- */
{id:'neuron_blocker', type:'class', level:4, char:'Adrenergic neuron blockers', meaning:['deplete norepinephrine'],
 reading:['severe hypertension (rarely used)'],
 info:'Reduce sympathetic activity by depleting or blocking NE storage/synthesis. Now rarely used.', requires:['ne']},
{id:'reserpine', type:'drug', level:4, char:'Reserpine', meaning:['adrenergic neuron blocker'],
 reading:['depletes monoamines; depression risk'],
 info:'Inhibits VMAT -> depletes NE, dopamine, serotonin (central + peripheral). ADR: depression / suicide risk.', requires:['neuron_blocker']},
{id:'guanethidine', type:'drug', level:4, char:'Guanethidine', meaning:['adrenergic neuron blocker'],
 reading:['replaces NE in vesicles'],
 info:'Taken into vesicles via VMAT, replaces NE -> depletes stores -> lower sympathetic output.', requires:['neuron_blocker']},
{id:'metyrosine', type:'drug', level:4, char:'Metyrosine', meaning:['tyrosine hydroxylase inhibitor'],
 reading:['blocks NE synthesis'],
 info:'Inhibits tyrosine hydroxylase (rate-limiting step) -> blocks catecholamine synthesis. Use: pheochromocytoma.', requires:['neuron_blocker']},
{id:'doxazosin', type:'drug', level:4, char:'Doxazosin', meaning:['alpha 1 blocker'],
 reading:['hypertension and BPH'],
 info:'Selective alpha1 blocker. Use: hypertension and BPH. ADR: first-dose orthostatic hypotension.', requires:['a_blocker']},
{id:'phentolamine', type:'drug', level:4, char:'Phentolamine', meaning:['nonselective alpha blocker'],
 reading:['reversible; pheochromocytoma'],
 info:'Nonselective competitive (reversible) alpha blocker. Use: short-term management of pheochromocytoma / catecholamine excess.', requires:['a_blocker']},
{id:'midodrine', type:'drug', level:4, char:'Midodrine', meaning:['alpha 1 agonist'],
 reading:['orthostatic hypotension'],
 info:'Selective alpha1 agonist (vasoconstrictor). Use: orthostatic hypotension.', requires:['a1_agonist']},
{id:'ephedrine', type:'drug', level:4, char:'Ephedrine', meaning:['mixed sympathomimetic'],
 reading:['alpha + beta; direct and indirect'],
 info:'Mixed-acting (direct alpha/beta + indirect NE release). CNS stimulant; older asthma/decongestant use.', requires:['a1_agonist']},
{id:'pseudoephedrine', type:'drug', level:4, char:'Pseudoephedrine', meaning:['alpha 1 agonist (decongestant)'],
 reading:['oral decongestant; meth precursor'],
 info:'Oral decongestant; controlled because it is a methamphetamine precursor.', requires:['a1_agonist']},
{id:'methylphenidate', type:'drug', level:4, char:'Methylphenidate', meaning:['indirect sympathomimetic'],
 reading:['ADHD and narcolepsy'],
 info:'CNS stimulant (blocks dopamine/NE reuptake). Use: ADHD, narcolepsy.', requires:['catecholamine']},
{id:'brimonidine', type:'drug', level:4, char:'Brimonidine', meaning:['alpha 2 agonist'],
 reading:['glaucoma; lowers aqueous humour'],
 info:'alpha2-selective agonist. Use: open-angle glaucoma (decreases aqueous humour production, increases outflow).', requires:['a2_central']},

/* ---- Level 5 (beta-blockers): more agents ---- */
{id:'bisoprolol', type:'drug', level:5, char:'Bisoprolol', meaning:['cardioselective beta 1 blocker'],
 reading:['heart failure'],
 info:'Cardioselective beta1 blocker. Use: heart failure (HFrEF), hypertension.', requires:['bblocker']},
{id:'esmolol', type:'drug', level:5, char:'Esmolol', meaning:['short acting beta 1 blocker'],
 reading:['IV; intra-operative / acute'],
 info:'Ultra-short-acting IV cardioselective blocker. Use: acute rate control, intra-operative HTN/tachycardia.', requires:['bblocker']},
{id:'pindolol', type:'drug', level:5, char:'Pindolol', meaning:['beta blocker with ISA'],
 reading:['partial agonist; less bradycardia'],
 info:'Nonselective blocker with intrinsic sympathomimetic activity (ISA) -> less bradycardia / less cardiac depression.', requires:['bblocker']},
{id:'nebivolol', type:'drug', level:5, char:'Nebivolol', meaning:['beta 1 blocker with vasodilation'],
 reading:['releases nitric oxide'],
 info:'Cardioselective beta1 blocker that also releases nitric oxide -> vasodilation. Use: hypertension.', requires:['bblocker']},

/* ---- Level 6 (cell wall): beta-lactamase inhibitors, polymyxins, more drugs ---- */
{id:'blactamase_inh', type:'class', level:6, char:'beta-lactamase inhibitors', meaning:['protect beta-lactams from beta-lactamase'],
 reading:['no antibacterial activity alone'],
 info:'Bind and inhibit beta-lactamase, protecting the partner beta-lactam. No antibacterial activity on their own. Combos: amox+clavulanate, pip+tazobactam.', requires:['penicillins']},
{id:'polymyxins', type:'class', level:6, char:'Polymyxins', meaning:['disrupt cell membrane'],
 reading:['MDR gram-negative; nephrotoxic'],
 info:'Cationic detergents that disrupt the gram-negative outer/cell membrane. Use: MDR gram-negative infections. ADR: nephrotoxicity, neurotoxicity.', requires:['bactericidal']},
{id:'ampicillin', type:'drug', level:6, char:'Ampicillin', meaning:['aminopenicillin'],
 reading:['food reduces absorption'],
 info:'Aminopenicillin (broader gram-negative). Food reduces absorption (take on empty stomach), unlike amoxicillin.', requires:['penicillins']},
{id:'clavulanate', type:'drug', level:6, char:'Clavulanic acid', meaning:['beta-lactamase inhibitor'],
 reading:['with amoxicillin = Augmentin'],
 info:'beta-lactamase inhibitor combined with amoxicillin (Augmentin).', requires:['blactamase_inh']},
{id:'tazobactam', type:'drug', level:6, char:'Tazobactam', meaning:['beta-lactamase inhibitor'],
 reading:['with piperacillin = Tazocin'],
 info:'beta-lactamase inhibitor combined with piperacillin (Tazocin) for mixed aerobic/anaerobic infections.', requires:['blactamase_inh']},
{id:'cefuroxime', type:'drug', level:6, char:'Cefuroxime', meaning:['2nd generation cephalosporin'],
 reading:['H. influenzae; community-acquired pneumonia'],
 info:'2nd-gen cephalosporin. Use: H. influenzae, community-acquired pneumonia.', requires:['cephalosporins']},
{id:'ceftaroline', type:'drug', level:6, char:'Ceftaroline', meaning:['5th generation cephalosporin'],
 reading:['covers MRSA'],
 info:'5th-gen cephalosporin -- notable for MRSA coverage.', requires:['cephalosporins']},
{id:'colistin', type:'drug', level:6, char:'Colistin', meaning:['polymyxin'],
 reading:['MDR gram-negative; nephrotoxic'],
 info:'Polymyxin E. Last-line for MDR gram-negative (e.g. carbapenem-resistant). ADR: nephrotoxicity.', requires:['polymyxins']},

/* ---- Level 7 (protein synthesis): more aminoglycosides / tetracyclines ---- */
{id:'streptomycin', type:'drug', level:7, char:'Streptomycin', meaning:['aminoglycoside'],
 reading:['tuberculosis; enterococcal endocarditis'],
 info:'Aminoglycoside. Use: second-line TB, enterococcal endocarditis (with a cell-wall agent).', requires:['aminoglycosides']},
{id:'tobramycin', type:'drug', level:7, char:'Tobramycin', meaning:['aminoglycoside'],
 reading:['Pseudomonas'],
 info:'Aminoglycoside with good Pseudomonas activity (inhaled in cystic fibrosis).', requires:['aminoglycosides']},
{id:'tetracycline_drug', type:'drug', level:7, char:'Tetracycline', meaning:['tetracycline'],
 reading:['chelates cations; empty stomach'],
 info:'Prototype tetracycline; chelates Ca/Mg/Al/iron (avoid dairy, antacids). Renal elimination.', requires:['tetracyclines']},
{id:'minocycline', type:'drug', level:7, char:'Minocycline', meaning:['tetracycline'],
 reading:['acne; good CNS penetration'],
 info:'Tetracycline with strong tissue/CNS penetration. Use: acne, some MRSA.', requires:['tetracyclines']},

/* ---- Level 8 (nucleic acid): rifamycins, more agents ---- */
{id:'rifamycins', type:'class', level:8, char:'Rifamycins', meaning:['inhibit RNA polymerase'],
 reading:['tuberculosis; strong CYP inducer'],
 info:'Inhibit bacterial DNA-dependent RNA polymerase. Use: tuberculosis, leprosy, prophylaxis. ADR: orange secretions, potent CYP450 induction.', requires:['bactericidal']},
{id:'rifampin', type:'drug', level:8, char:'Rifampin', meaning:['rifamycin'],
 reading:['TB; potent CYP450 inducer; orange fluids'],
 info:'Rifamycin -- RNA polymerase inhibitor. Cornerstone of TB therapy. Strong CYP inducer; orange-red secretions.', requires:['rifamycins']},
{id:'norfloxacin', type:'drug', level:8, char:'Norfloxacin', meaning:['fluoroquinolone'],
 reading:['uncomplicated UTI'],
 info:'Older fluoroquinolone. Use: uncomplicated UTI (gram-negative).', requires:['fluoroquinolones']},
{id:'sulfasalazine', type:'drug', level:8, char:'Sulfasalazine', meaning:['sulfonamide'],
 reading:['ulcerative colitis; rheumatoid arthritis'],
 info:'Non-absorbable sulfonamide split into sulfapyridine + 5-aminosalicylate. Use: ulcerative colitis, rheumatoid arthritis.', requires:['folate_inhibitors']},
{id:'silver_sulfadiazine', type:'drug', level:8, char:'Silver sulfadiazine', meaning:['topical sulfonamide'],
 reading:['burn wounds'],
 info:'Topical sulfonamide. Use: prevention of burn-wound infection.', requires:['folate_inhibitors']},

/* ---- Level 9 (antifungals): broad-spectrum azoles, topical, echinocandin ---- */
{id:'posaconazole', type:'drug', level:9, char:'Posaconazole', meaning:['azole (triazole)'],
 reading:['broadest azole; covers Mucor'],
 info:'Broadest-spectrum azole; first azole active against Mucormycosis. Prophylaxis in immunocompromised.', requires:['azoles']},
{id:'isavuconazole', type:'drug', level:9, char:'Isavuconazole', meaning:['azole (triazole)'],
 reading:['covers Mucor; better tolerated'],
 info:'Newest triazole (prodrug). Covers Aspergillus and Mucor; fewer visual/photo side effects than voriconazole.', requires:['azoles']},
{id:'clotrimazole', type:'drug', level:9, char:'Clotrimazole', meaning:['azole (imidazole, topical)'],
 reading:['vaginal candidiasis; tinea'],
 info:'Topical imidazole. Use: vaginal candidiasis, tinea, oral thrush.', requires:['azoles']},
{id:'micafungin', type:'drug', level:9, char:'Micafungin', meaning:['echinocandin'],
 reading:['candidemia; IV only'],
 info:'Echinocandin (IV). Use: candidemia, esophageal candidiasis, prophylaxis.', requires:['echinocandins']},

/* ---- Level 10 (antivirals): interferons, more herpes/HBV agents ---- */
{id:'interferon_stem', type:'stem', level:10, char:'Interferon', meaning:['innate antiviral cytokine'],
 mnemonic:'Interferon INTERFERES with viral copying -- your cells innate alarm signal.',
 info:'Host cytokine that triggers antiviral proteins via the JAK-STAT pathway (Mx, RNase L, PKR).', requires:[]},
{id:'interferons', type:'class', level:10, char:'Interferons', meaning:['broad antiviral cytokines'],
 reading:['flu-like syndrome adverse effect'],
 info:'Recombinant / pegylated interferons induce broad antiviral state. ADR: acute flu-like syndrome, fatigue, depression.', requires:['interferon_stem']},
{id:'peg_interferon', type:'drug', level:10, char:'PEG-interferon', meaning:['pegylated interferon'],
 reading:['chronic HBV/HCV; weekly'],
 info:'Pegylation extends half-life -> once-weekly dosing. Use: chronic HBV, (historically) HCV.', requires:['interferons']},
{id:'famciclovir', type:'drug', level:10, char:'Famciclovir', meaning:['penciclovir prodrug'],
 reading:['HSV and VZV'],
 info:'Diacetyl ester prodrug of penciclovir. Use: HSV recurrence, VZV (zoster); good oral bioavailability.', requires:['anti_herpes']},
{id:'lamivudine', type:'drug', level:10, char:'Lamivudine', meaning:['anti-HBV nucleoside analog'],
 reading:['resistance develops easily'],
 info:'Nucleoside analog inhibiting HBV reverse transcriptase. Resistance (YMDD mutation) develops readily.', requires:['hbv_drugs']},
{id:'adefovir', type:'drug', level:10, char:'Adefovir', meaning:['anti-HBV nucleotide analog'],
 reading:['nephrotoxic; less used'],
 info:'Nucleotide analog for HBV; limited by resistance and nephrotoxicity.', requires:['hbv_drugs']},

/* ---- Level 11 (HCV): more DAAs ---- */
{id:'velpatasvir', type:'drug', level:11, char:'Velpatasvir', meaning:['ns5a inhibitor'],
 reading:['pangenotypic with sofosbuvir'],
 info:'NS5A inhibitor; sofosbuvir/velpatasvir (Epclusa) is a pangenotypic HCV regimen.', requires:['daa']},
{id:'daclatasvir', type:'drug', level:11, char:'Daclatasvir', meaning:['ns5a inhibitor'],
 reading:['HCV combination therapy'],
 info:'NS5A inhibitor used in combination HCV regimens.', requires:['daa']},
{id:'glecaprevir', type:'drug', level:11, char:'Glecaprevir', meaning:['ns3 4a protease inhibitor'],
 reading:['with pibrentasvir (Mavyret)'],
 info:'NS3/4A protease inhibitor; glecaprevir/pibrentasvir is a pangenotypic regimen.', requires:['previr']},
{id:'simeprevir', type:'drug', level:11, char:'Simeprevir', meaning:['ns3 4a protease inhibitor'],
 reading:['HCV combination therapy'],
 info:'NS3/4A protease inhibitor used with other DAAs.', requires:['previr']},

/* ---- Level 12 (cytotoxic): more agents, rescue drugs, leukemia adjuncts ---- */
{id:'ifosfamide', type:'drug', level:12, char:'Ifosfamide', meaning:['alkylating agent'],
 reading:['hemorrhagic cystitis; MESNA'],
 info:'Prodrug alkylating agent; like cyclophosphamide produces acrolein -> hemorrhagic cystitis (give MESNA + hydration).', requires:['alkylating']},
{id:'capecitabine', type:'drug', level:12, char:'Capecitabine', meaning:['oral 5-FU prodrug'],
 reading:['hand-foot syndrome'],
 info:'Oral prodrug activated to 5-FU in tumour. ADR: hand-foot syndrome, stomatitis.', requires:['antimetabolites']},
{id:'daunorubicin', type:'drug', level:12, char:'Daunorubicin', meaning:['anthracycline'],
 reading:['acute leukemia; cardiotoxic'],
 info:'Anthracycline (topoisomerase II inhibitor). Use: acute leukemias. ADR: cardiotoxicity.', requires:['anthracyclines']},
{id:'leucovorin', type:'drug', level:12, char:'Leucovorin', meaning:['methotrexate rescue'],
 reading:['folinic acid; bypasses DHFR'],
 info:'Folinic acid that bypasses DHFR -> rescues normal cells after high-dose methotrexate; also potentiates 5-FU.', requires:['antimetabolites']},
{id:'mesna', type:'drug', level:12, char:'MESNA', meaning:['uroprotectant'],
 reading:['prevents hemorrhagic cystitis'],
 info:'Binds acrolein in the bladder -> prevents hemorrhagic cystitis from cyclophosphamide/ifosfamide.', requires:['alkylating']},
{id:'dexrazoxane', type:'drug', level:12, char:'Dexrazoxane', meaning:['cardioprotectant'],
 reading:['iron chelator; doxorubicin'],
 info:'Iron chelator that reduces anthracycline (doxorubicin) cardiotoxicity.', requires:['anthracyclines']},
{id:'lasparaginase', type:'drug', level:12, char:'L-Asparaginase', meaning:['enzyme therapy'],
 reading:['childhood ALL; depletes asparagine'],
 info:'Depletes extracellular asparagine, which leukemic cells cannot synthesize. Use: childhood ALL. ADR: hypersensitivity, raised PT/PTT; no marrow suppression.', requires:['ccs']},
{id:'prednisolone_onc', type:'drug', level:12, char:'Prednisolone (onco)', meaning:['corticosteroid'],
 reading:['lymphocyte apoptosis; leukemia/lymphoma'],
 info:'Glucocorticoid causing lymphocyte apoptosis (lympholysis). Use: leukemia, lymphoma regimens.', requires:['ccs']},

/* ---- Level 13 (targeted/hormonal): SERD, steroidal AI, EGFR TKI ---- */
{id:'serd', type:'class', level:13, char:'SERDs', meaning:['estrogen receptor degraders'],
 reading:['pure antagonist'],
 info:'Selective estrogen-receptor down-regulators -- pure antagonists that cause ER degradation (no uterine agonism).', requires:['er_pr']},
{id:'fulvestrant', type:'drug', level:13, char:'Fulvestrant', meaning:['serd'],
 reading:['pure antagonist; intramuscular'],
 info:'SERD given intramuscularly; degrades ER-alpha. No endometrial cancer risk. Use: ER+ breast cancer.', requires:['serd']},
{id:'exemestane', type:'drug', level:13, char:'Exemestane', meaning:['steroidal aromatase inhibitor'],
 reading:['irreversible'],
 info:'Steroidal, irreversible aromatase inhibitor. Use: postmenopausal ER+ breast cancer.', requires:['aromatase_inh']},
{id:'erlotinib', type:'drug', level:13, char:'Erlotinib', meaning:['egfr tyrosine kinase inhibitor'],
 reading:['NSCLC; acneiform rash'],
 info:'EGFR TKI. Use: NSCLC with EGFR activating mutation. ADR: acneiform rash, diarrhea.', requires:['tki']}

];
